name: app_visibility_manager
description: A Flutter package to manage UI visibility based on the app's lifecycle state.
version: 0.0.2
repository: https://github.com/emrhnzngn/app_visibility_manager
issue_tracker: https://github.com/emrhnzngn/app_visibility_manager/issues
homepage: https://github.com/emrhnzngn/app_visibility_manager

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter: